image: node:alpine
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
  variables:
<<<<<<< HEAD
    PUBLIC_URL: "/todo-part-3" # slash is important
=======
    PUBLIC_URL: "/todo-part-2"
>>>>>>> 8c4fc01171c95249001a63fe971dc8da43c5afdc
